name: Build and deploy .NET Core app to Linux WebApp task-runner-besmir
on:
  push:
    branches:
    - master
env:
  AZURE_WEBAPP_NAME: task-runner-besmir
  AZURE_WEBAPP_PACKAGE_PATH: TaskChecklist/publish
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.task_runner_besmir_4440 }}
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: TaskChecklist
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      Version: ${{ steps.gitversion.outputs.SemVer }}
      CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v1.2.0
      with:
        versionSpec: 5.x
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v1.2.0
    - name: Display GitVersion outputs
      run: |
        echo "Version: ${{ steps.gitversion.outputs.SemVer }}"
        echo "CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}"
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"

    # - name: Test
    #   run: dotnet test "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }}

    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}/TaskChecklist.csproj" --configuration ${{ env.CONFIGURATION }} -p:Version='${{ steps.gitversion.outputs.SemVer }}' --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

  #  - name: Deploy to Azure WebApp
  #    uses: azure/webapps-deploy@v2
  #    with:
  #      app-name: ${{ env.AZURE_WEBAPP_NAME }}
  #      package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  #      publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
  
    - name: Publish Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
